= Game On!
:icons: font

*https://game-on.org[Try Game On! Now]*

_You are in a maze of little interconnected rooms, none alike._

Game On! is a both a sample microservices application, and throwback text adventure brought to you by the https://wasdev.net[wasdev] team at IBM. It aims to do a few things: 

* Provide a sample microservices-based application.

* Demonstrate how microservice architectures work from two points of view:
** As a Player: Naviagate through a network/maze of rooms, where each room is a unique implementation of a common API. Each room supports chat, and interaction with items (some of which may be in the room, some of which may be separately defined services as well). 

** As a Developer: Learn about microservice architectures and supporting infrastructure by extending the game with your own services. Write additional rooms or items and see how they interact with the rest of the system.

Check out the links to the left for more information about Game On!'s architecture, or https://game-on.org[Start Playing] now.