= Game On!

_You are in a maze of little interconnected rooms, none alike._

Game On! is a both a sample microservices application, and throwback text adventure. For more information, see http://game-on.org/docs, or you might prefer to skip all that business and just [Go Play!](http://game-on.org/).

Game On! is a text-based throwback adventure brought to you by the https://wasdev.net[wasdev] team at IBM. It aims to do a few things: 

* Provide a sample microservices-based application
* Demonstrate how microservice architectures work from two points of view
** Interact with and navigate through the system as a player: each room is a unique service, "leaderboards" are maintained via service logging and metrics, etc.
** Interact with the system as a developer: Developers can create and contribute their own services to the system, allowing them to provide and interact with a microservices architecture in a direct way without having to stand one up themselves.


*https://game-on.org[Play Now!]*



## About Game On!

Game On! was built to mimic a chat service with the ability to interact with various objects as well as other
players inside a virtual world, much in the same light as many https://en.wikipedia.org/wiki/Massively_multiplayer_online_role-playing_game[MMORPGs] in the same vein as the
https://en.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy_%28video_game%29[Hitchhiker's Guide Video Game].

Use the links to the left to enjoy our GitBook and read more about Game On!

