= Getting Started: Build your own room
:icons: font
:toc: preamble
:toclevels: 1
:sectanchors:

We'll cheat a little bit here: to do this mad dash from nothing to everything, you have to have Java 1.8, Node.js, Git, and Docker already set up. If you don't, then visit the link:git.adoc[Git], link:requirements.adoc[prerequisites], and the link:local-docker.adoc[docker requirements] pages to make sure you're good to go.

== Get the source

Recursively grab all the source for our core modules, and change to the new shiny cloned directory: 

----
git clone --recursive https://github.com:gameontext/gameon.git
cd gameon
----

== Build the applications

Build the submodules that contain gradle.

----
./build.sh
----

== Docker compose: Game On!

To start up the whole collection using `docker-compose`, run the following:

----
docker-compose build
docker-compose up
----

The game is now running locally, you can access it at http://127.0.0.1/ or at your docker-machine host's ip address.

.Use the right IP address
[NOTE]
=========
If you run on an operating system that uses a host VM for docker images (e.g. Windows or Mac), then you need to update some values in `gameon.env` to match the IP address of your host. The host IP address is returned by `docker-machine ip <machine-name>`.

`build.sh` will create a customized copy of `gameon.env` for the active DOCKER_MACHINE_NAME, that will perform the substitution to the associated IP address.
=========


[[incrementalPublish]]
== Top-down vs. incremental updates

It is possible to make application updates outside of the container during development: we do this with the overlay function supported by docker compose.

`docker-compose.override.yml.example` maps subrepository paths into the docker containers to support live development. Rename the file to `docker-compose.override.yml`, or copy it and edit as you see fit.

If you intend to make updates to the web front end (in webapp), make sure you have node installed, and then build the webapp project:

----
cd webapp
npm install
./node_modules/.bin/grunt build
----






