= Advanced Adventure for X,Y,Z
:icons: font
:toc:
:toc-title:
:toc-placement: preamble
:toclevels: 2
:linkref: http://www.google.com

Where we learn about X,Y,X

++++
<script>
function walkthroughLang(evt, language) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(language).style.display = "block";
    evt.currentTarget.className += " active";
}
</script>
++++

## Overview

This adventure will teach you about X,Y,Z by walking you through the process of adding A,B,C to a Game On room.
You will come away having learnt a little about X,Y,Z and there will be suggestions for how you can use this further
within a room.

## Why X,Y,Z ?

Describe X,Y,Z. Mention why it is important for Microservices in general, rather than a Game On Room.
Give examples the types of things user would do with X,Y,Z today. 
Give a 1-2 sentence overview of what you will guide the user through in your walkthrough.

## Prerequisites

Does this walkthrough build on any other? does it require a Bluemix service instance? External sign ups for accounts?
Assume the user has a Game-On player id, and has followed the basic 'Get a Room Running in Game On' tutorial.
Any other accounts, services, etc should be explained at this point, with links and ideally screenshots guiding the user through creation.

## Walkthrough
++++
<ul class="tab">
  <li><a href="javascript:void(0)" class="tablinks" onclick="walkthroughLang(event, 'java')">Java</a></li>
  <li><a href="javascript:void(0)" class="tablinks" onclick="walkthroughLang(event, 'javascript')">JS</a></li>
  <li><a href="javascript:void(0)" class="tablinks" onclick="walkthroughLang(event, 'go')">Go</a></li>
</ul>
++++

++++
<div id="java" class="tabcontent">
++++
Guide the user through, step by step, suggested order of .. 

* adding dependencies to the pom.xml
* adding basic code snippets
** explain each change to each file, why are you making this change, what does it give the user.
* adding a simple test case & verifying execution
** because tests are important.
* provide a way for the user to invoke X,Y,Z while running in game on.
** guide the user through /sos,/teleport roomid,invoking the function, and seeing the result.
* link to a repo/branch where all the above has been done, and the user has the minimum to do to test the X,Y,Z

TIP: Use tips to call out interesting things. 
++++
</div>
++++

++++
<div id="javascript" class="tabcontent">
++++

Javascripty stuff.. 

++++
</div>
++++

## Suggested extensions

Talk about extra things the user could do with X,Y,Z that were not covered here
Note, we're not talking here about other technologies or stuff covered by other adventures
Keep this limited to additional ways to use X,Y,Z that were omitted due to time/space, etc
Especially include any common way to use X,Y,Z that is not demonstrated in the walkthrough.

## Conclusion

Explain what the user has learnt by following this tutorial.

## Suggested further adventures.

Link to adventures that can build from this one 
(try to revisit your advanced adventure periodically to add additional ones)
