= Overview of Microservices
:icons: font
:imagesdir: /images


Microservices initially gained attention as the development approach being used by the large Internet companies such as Netflix, Google, Facebook, and Twitter. We could say that microservices grew from solving the real world problems this type of digital-only company faced. Their key business asset, their applications, needed to scale for global demand and be highly resilient.  At the same time, these applications needed to remain very nimble and fresh, with new updates rolling out at a steady and frequent pace.

Now with wider adoption, the approach has been refined through experience and the demands of different types of business. As a result, microservices are now ready for prime-time adoption.  The challenges introduced with the microservices approach are well understood, and the technology enabling the critical automation needed for microservices delivery has matured, making success an attainable goal.

While there is no formal standards body definition for microservices, we can describe it in a nutshell as an application architecture where a single application is composed of a suite of small services or microservices, which have the following characteristics:

* Services are autonomous, enabling independent update and deployment
* Services are defined by business capabilities
* Services run in their own process
* Services communicate over the light-weight network protocols
* Services are choreographed or orchestrated together to form the application
* Polyglot runtimes enable use of the best language for the service task
* Polyglot persistence use the best data storage for the service task

It is also useful to keep in mind the three key outcomes of a microservices-based approach. Decomposition of a monolithic application into microservices should result in an application with that is: 

* *Resilient*– Will survive component failure with minimum end user impact
* *Agile*– Enables fast and frequent change with minimum risk
* *Scalable*– Will automatically scale up to meet global demands



