= Deploying to IBM Bluemix using a Docker Container
:icons: font
:toc: preamble
:toc-title:
:toclevels: 2
:cficDoc: https://console.ng.bluemix.net/docs/containers/container_cli_cfic.html
:roomRegistration: link:registerRoom.adoc

{empty}

== Prerequisites for Bluemix deployment

- https://console.ng.bluemix.net[Bluemix account] / https://console.ng.bluemix.net/docs/admin/account.html[Signing up for Bluemix]
- https://docs.cloudfoundry.org/cf-cli/[Cloud Foundry command line]
- https://console.ng.bluemix.net/docs/containers/container_cli_cfic_install.html[Install the IBM Containers plugin]

== Create Bluemix accounts

If you already have a Bluemix account, you can skip right over this section.

Sign up for Bluemix at https://console.ng.bluemix.net
When you sign up, you'll create an IBM ID, create an alias, and
register with Bluemix.

* Make a note of your username and org, as you will need both later.
  - By default, the space is `dev` and the org is the project creator's user name.
    For example, if sara@example.com signs in to Bluemix for the first time,
    the active space is `dev` and the org is `sara@example.com`.

* Make a note of your region! (US South, United Kingdom, or Australia)
  - When you log into Bluemix, your logged in username, organization, and
    space are shown in the top right. If you click in the top right corner,
    you'll see the region displayed in the panel displayed on the right side
    of the screen.

== Log in using the `cf` command

See the {cficDoc}[IBM Bluemix Container Service plug-in] documentation
for the latest instructions, what follows is the TL;DR version:

1. Login to Bluemix via the command line:
+
    cf login
+
  - Enter Bluemix API endpoint (for your region):
    * US South: `https://api.ng.bluemix.net`
    * London: `https://api.eu-gb.bluemix.net`
  - Enter email and password for Bluemix login
    * If logging in with a federated ID (if you don't know what this means,
      you aren't), use the `-sso` option with a
      https://login.ng.bluemix.net/UAALoginServerWAR/passcode[one-time use password]
  - Choose a Bluemix organization by number
  - Choose a Bluemix space by number

2. If this is your first time logging in to Bluemix, create a namespace.
   This step happens only once, and can't be changed, so choose well:
+
    cf ic namespace set <my_namespace>
+
    - Use only letters, numbers, or underscores
    - Use 4 to 30 characters

2. Login with the IBM Container service:
+
    cf ic init
+
This will create the keys and certificates required to work with
   the Bluemix docker image registry.

== Add the docker image to the IBM Container service registry

1. Use `cf ic` commands to build the docker container and push it into the Bluemix registry.
   Use the `-t <tagName>` option to tag the image.
  - For the `sample-room-java` project, from the application root directory, use

    cf ic build -t gojava .

2. Run `cf ic images` and check that your image is in the list.

See the Bluemix documentation for more information about
https://console.ng.bluemix.net/docs/containers/container_images_pulling.html{pushing local images to the Bluemix Registry}

== Deploy a single container

1. Start the container by running the command `cf ic run`. You can find the full path to the image
   from the output of `cf ic images`.
  - For the `sample-room-java` project, as an example:
+
    cf ic run -p 9080 --name gojava registry.ng.bluemix.net/<your-org>/gojava

2. Bind a public IP address to your container
   - Get a public IP address
+
    cf ic ip request
+
   - Bind it to your running container:
+
    cf ic ip bind <ip address> <tagName>

7. Use `cf ic ps` to check the status of your container. Wait for it to switch from "Networking" to "Running"

8. Use the public IP address to visit your running container
  - For the `sample-room-java` project, use `http://<ip address>:9080/` to access the application.
  - Copy the websocket endpoint address. Use this address in your {roomRegistration}[room registration].

== Deploy as a container group

Instead of deploying a container as a single instance, you can instead deploy a
container group. A container group load balances between multiple instances of
the same container.

3. Create the container group:
+
    cf ic group create -p 9080 -n <appName> --name <groupName> <registry>/<namespace>/<tagName>
+
You can find the full path to the image from the output of `cf ic images`.

  - For the `sample-room-java` project, an example would be:
+
    cf ic group create -p 9080 --name gojavagroup registry.ng.bluemix.net/<org-name>/gojava

4. Make your containers publicly available at <appHost>.mybluemix.net:
+
    cf ic route map -n <appHost> -d mybluemix.net <groupName>

5. Check the status of your instances
+
   cf ic group instances <groupName>
+
Once they are in "Running" state your group is ready to use.

6. Now you can go to `http://<appHost>.mybluemix.net` to access your application.
  - Copy the websocket endpoint address. Use this address in your {roomRegistration}[room registration].
