= Extending the Game
:icons: font
:createRoom: link:createRoom.adoc
:createNPC: link:createNPC.adoc
:whatNext: link:createMore.adoc

As has been mentioned, this game was built to be extended.

Creating rooms or non-player characters or quantum-entangled items is not
really the point, though it has the advantage of giving you something to build
that isn't so closely related to traditional patterns you already know.

The point is for you to experiment with microservice architectures and strategies
for building resilient distributed systems. We have some walkthroughs to get
you started:

{createRoom}[Create a new room]::
Use Cloud Foundry applications or Docker containers to build and deploy
microservices that add additional rooms to the game.

//{createNPC}[Create a non-player character]::
//Use Whisk actions to create non-player characters that respond to triggers from
//inside or outside of the game.

{whatNext}[Choose your own adventure]::
Choose from a list of follow-on activities to improve the scalability and
resilience of your room, or to create new inter-service interaction patterns.
