= Signed requests
:icons: font
:toc:
:toc-placement: manual
:toclevels: 1

{empty}

This is the definition of how signed requests are used by GameOn. It details how they are constructed, transmitted and parsed. 

== Signed requests using HTTP/REST
A signed request can be sent to GameOn using HTTP headers, as part of the query string or a combination of both. The request is made up of a number of component parts, all of which must be present, but you are free to choose whether you supply them in a header or query string parameter. Duplicate entries i.e. where you have a header and parameter with the same name, will be treated as an invalid request. The following table lists the values that need to be supplied

| Name | Description | Required | Notes |
| ---- | ----------- | -------- | ----- |
| *gameon-id* | Your room public API key. | Required | When you obtain a room API key from GameOn you are given a public key and a secret. The public key identifies the room instance and the developer that created it. |
| *gameon-date* | The time and date when the request was created. | Required | Remember to convert the date/time to universal time. Failure to do so will result in the request failing. |
| *gameon-signature* | Signature to be validated | Required | The signature is a case insensitive hex string. |
| *gameon-sig-headers* | The list of headers which are part of the signature, followed by a hash of the header list. | Optional | Headers are a semi-colon delimited list. This must not include any of the ** gameon-* ** names. |
| *gameon-sig-params* | The list of query parameters which are part of the signature, followed by a hash of the parameter list. | Optional | Parameters are a semi-colon delimited list. This must not include any of the ** gameon-* ** names even if you are passing them as parameters. |
| *gameon-sig-body* | Hash of the contents of the body of any request. | Optional | Typically used to ensure that JSON sent to the server has not been modified in transit. |

Note : each API will define which headers and/or parameters are required to be part of the signature, gameon-date is the only mandatory value required by all APIs.

== How to construct the gameon-signature
In order for GameOn to validate any supplied signature, the following steps need to be followed when creating your signature

Note : unless otherwise stated, GameOn uses the SHA-256 algorithm to generate or validate hashes.

1. Create the **gameon-sig-headers** value (if required)
   a. For each HTTP header that is to be part of the signature
      .. Add the name to the list of headers (entries are delimited by semi-colons)
      .. Append the value to a hash (typically this is done by repeatedly calling a hash function)
   b. Calculate the hash from all the appended values and add it to the end of the **gameon-sig-headers** value as a lower case hex string.
1. Create the **gameon-sig**-parameters value (if required)
   a. Follow the same procedure as for headers detailed in step 1.
1. Create the **gameon-sig-body** value (if required) by hashing the contents of the request body.
   a. Convert the current time and date to UTC and store in **gameon-date**
1. Put your public API key in **gameon-id**.
1. Create the **gameon-signature** value
   a. Initialise a HMAC-SHA256 function
   a. The secret for the HMAC is your API secret.
   a. Add the value of **gameon-id**
   a. Add the value of **gameon-date**
   a. Add the value of **gameon-sig-headers** (if present)
   a. Add the value of **gameon-sig-parameters** (if present)
   a. Add the value of **gameon-sig-body** (if present)
   a. Generate the HMAC, convert it to lowercase hex, and store in **gameon-signature**.

== Examples

1) A signed GET request which includes the Content-Type HTTP header in the signature.
```
GET http://gameon.org/map HTTP/1.1
Content-Type: application/json
gameon-id: MyPublicRoomID
gameon-date: 20160212T114600Z
gameon-sig-headers: Content-Type;56a65fb554ccc3
gameon-signature: 879bca12f2314cd
```

2)  A signed POST request which signs the JSON body content
```
POST http://gameon.org/..... HTTP/1.1
Content-Type: application/json
gameon-id: MyPublicRoomID
gameon-date: 20160212T114600Z
gameon-sig-body: fe272346cadd
gameon-signature: 834534aaa314cd

{id='test'}
```

3) A signed request that mixes headers and parameters, **gameon-date** is not included in the **gameon-sig-params** field as it is already used elsewhere in the signature process.
```
GET http://gameon.org/map?gameon-date=20160212T114600Z&type=all&format=json HTTP/1.1
Content-Type: application/json
gameon-id: MyPublicRoomID
gameon-sig-headers: Content-Type;56a65fb554ccc3
gameon-sig-params: type;format;45fadd33
gameon-signature: 879bca12f2314cd
```

== How GameOn parses signed requests
When GameOn receives a signed request, it carries out a series of validation and verification steps before processing it. If at any point this fails, then for security reasons, the client will be given a 404 error with no indication as to why the request failed.

The process that Game On! performs is as follows

1. Examines the value of **gameon-id** and ensures that
  a. It is valid i.e. issued to a registered room developer
  a. Has not been revoked
1. Generates the value of **gameon-signature** using the steps described in 'How to construct the gameon-signature'
  a. It uses the secret that is paired with the supplied **gameon-id**
  a. Checks that the signatures match - the shared secret confirms the identity of the sender.
1. Examines the value of **gameon-date** and ensures that
  a. The request is not older than 5 minutes
  a. If the request is less than 5 minutes old, then the signature does not match a previously received request
1. Examines the value **gameon-sig-headers** (if present)
  a. Generates a hash from the specified header values
  a. Checks that the hash matches the request.
1. Examines the value **gameon-sig-params** (if present)
  a. Generates a hash from the specified parameter values
  a. Checks that the hash matches the request.
1. Examines the value **gameon-sig-body** (if present)
  a. Generates a hash from the request body
  a. Checks that the hash matches the request.

== When to use signed requests
TBD : Details of which APIs require signed requests.

== Things to watch out for
* Headers being added or altered by post processing steps e.g. passing through a Java EE filter.

== How to get an API key
TBD : this needs it's own GitBook entry

== References
1. List of standard HTTP headers and well known non-standard ones :  https://tools.ietf.org/html/rfc7235
1. How to define custom HTTP headers : http://tools.ietf.org/html/rfc6648

A quick note about custom HTTP headers. Originally it was recommended that custom headers start with x-, so this is why you see headers such as x-api-key and x-amz-date. However in the latest RFC, this has been changed to say that you should use something meaningful, and it no longer needs to be prefixed with x-. If you want to avoid potential name space clashes then try and use something unique to your application or organisation. So, this is why the GameOn custom HTTP headers do not start with x- (in case anyone asks).



