= Signed tokens
:icons: font
:toc:
:toc-placement: preamble
:toclevels: 1
:jwt-java: https://github.com/jwtk/jjwt
:jsrsasign: http://kjur.github.io/jsrsasign/
:jwt-struct: http://jwt.io/introduction/


{toc}

This is the definition of how signed tokens are used by GameOn. It details how they are constructed, transmitted and parsed. 

== Signed tokens using HTTP/REST

Game On! uses signed JSON web tokens (JWT) to transfer data between entities. Server code is processed using {jwt-java}[Java JWT: JSON Web Token for Java]. JavaScript clients use {jsrsasign}[jsrsasign] to validate received JWTs.

== How GameOn parses signed tokens

When a Game On! service requires a signed token it performs the following validation and verification.

1. Validate that a query string has been supplied
1. Check that there is a single parameter named * jwt *
1. Parse the parameter into a JWT
1. Validate that the signature matches the claims

Signed tokens are passed as a query string parameter, but could also be passed as an HTTP header instead.

== Example signed JWT

The query parameter is base 64 encoded :

```
eyJraWQiOiJwbGF5ZXJzc2wiLCJhbGciOiJSUzI1NiJ9.eyJuYW1lIjoiZmlzaCIsImlkIjoiZHVtbXkuZmlzaCIsInN1YiI6ImR1bW15LmZpc2giLCJhdWQiOi
JjbGllbnQiLCJpYXQiOjE0NTU3Mjc0NjEsImV4cCI6MTQ1NTkwMDI2MX0.OM6jOpx0xnj_Hfojttlz2fWmztkS7EY2pHVttHaQuSPW-b0zwn9G3XN5b1rleavRS
pQ-CPOfYhfyQuO2JaSfzkoEZbOaqRSEGEKZo3DE4jG8cOciEsgldd487j4AoY1_NnjAYMH5yDI9jtMAiiYjMty1dq5YP3UIt4mac1GOx5FPE8Lr35e9uMKT8eqW
QUXRl3feJIz26kTsF2HL6guSK1AumUTMpLQFGH0MENIJQtL_5SOHKbMnPmk6gNkZcSb6LN_sVCf1KilqyIm1OCTylV8yq8YN5AT9vOQP3lwrFvyKYlOulTI4Gs_
-inO5y3VbWzsvvcIlhecaEcCYqb6E6Q
```

When decoded, this gives a header of 

```
{
  "kid": "playerssl",
  "alg": "RS256"
}
```

and a payload of 

```
{
  "name": "fish",
  "id": "dummy.fish",
  "sub": "dummy.fish",
  "aud": "client",
  "iat": 1455727461,
  "exp": 1455900261
}
```

== How to construct a GameOn signed token
Game On! JWTs are created and signed according to the method described in the "Which is the JSON Web Token Structure" section of the {jwt-struct}[introduction to JWTs] at http://jwt.io.

The claims used as those specified by https://tools.ietf.org/html/rfc7519#section-4.1.

Note : unless otherwise staties, Game On! uses *RS256* as the signature algorithm.

== Useful links

* Testing your JWT : http://jwt.io/#debugger-io
* Browser JS for working with JWT's, {jsrsasign}[{jsrsasign}]
* Server side JTW processing with JJWT : {jwt-java}[{jwt-java}]
* JSON Web Token RFC : https://tools.ietf.org/html/rfc7519

